version: '3.9'
services:
  tamanotchi-postgres:
    image: tamanotchi-db
    hostname: postgres
    env_file:
      - .env.postgres
    ports:
      - 5432:5432
  tamanotchi-frontend:
    image: tamanotchi-front
    ports:
      - 3000:3000
  tamanotchi-backend:
    depends_on:
      - tamanotchi-postgres
    environment:
      - DB_HOST=postgres
    image: tamanotchi-back
    ports:
      - 8080:8080